=== flexicious/react-data-grid/apps/lambda-genie-demo/shared/lambda-genie/setup/schema/ColumnConfig.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://example.com/column-options.schema.json",
    "title": "ColumnConfig",
    "type": "object",
    "properties": {
        "headerText": {
            "type": "string"
        },
        "dataField": {
            "type": "string"
        },
        "uniqueIdentifier": {
            "type": "string"
        },
        "format": {
            "type": "string",
            "enum": [
                "string",
                "number",
                "date",
                "dateTime",
                "currency",
                "boolean"
            ]
        },
        "width": {
            "type": "number"
        },
        "widthMode": {
            "type": "string",
            "enum": [
                "percent",
                "fixed",
                "fitToContent"
            ]
        },
        "lockMode": {
            "type": "string",
            "enum": [
                "none",
                "left",
                "right"
            ]
        },
        "textAlign": {
            "type": "string",
            "enum": [
                "center",
                "right"
            ]
        },
        "hidden": {
            "type": "boolean"
        },
        "percentWidth": {
            "type": "number"
        },
        "formatterPrecision": {
            "type": "number"
        },
        "excludeFromPdf": {
            "type": "boolean"
        },
        "excludeFromExcel": {
            "type": "boolean"
        },
        "textWidthAdjustment": {
            "type": "number"
        },
        "enableHierarchy": {
            "type": "boolean"
        },
        "enableSort": {
            "type": "boolean"
        },
        "enableResize": {
            "type": "boolean"
        },
        "enableMove": {
            "type": "boolean"
        },
        "enableDrag": {
            "type": "boolean"
        },
        "excludeFromSettings": {
            "type": "boolean"
        },
        "enableCellClickRowSelect": {
            "type": "boolean"
        },
        "enableFocus": {
            "type": "boolean"
        },
        "enableColumnMenu": {
            "type": "boolean"
        },
        "sortOptions": {
            "$ref": "#/definitions/SortOptions"
        },
        "editOptions": {
            "$ref": "#/definitions/EditOptions"
        },
        "headerOptions": {
            "$ref": "#/definitions/HeaderOptions"
        },
        "footerOptions": {
            "$ref": "#/definitions/FooterOptions"
        },
        "filterOptions": {
            "$ref": "#/definitions/FilterOptions"
        },
        "variableRowHeightOptions": {
            "$ref": "#/definitions/VariableRowHeightColumnOptions"
        }
    },
    "definitions": {
        "FooterOptions": {
            "type": "object",
            "properties": {
                "footerOperation": {
                    "type": "string",
                    "enum": [
                        "Sum",
                        "Avg",
                        "Min",
                        "Max",
                        "Count",
                        "Median"
                    ]
                },
                "footerOperationPrecision": {
                    "type": "integer",
                    "minimum": 0
                },
                "footerLabel": {
                    "type": "string"
                },
                "enableFooterMenu": {
                    "type": "boolean"
                },
                "footerDataField": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "HeaderOptions": {
            "type": "object",
            "properties": {
                "columnGroupText": {
                    "type": "string"
                },
                "columnGroupTooltip": {
                    "type": "string"
                },
                "headerTooltip": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "VariableRowHeightColumnOptions": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            },
            "additionalProperties": false
        },
        "EditOptions": {
            "type": "object",
            "properties": {
                "editStartMode": {
                    "type": "string",
                    "enum": [
                        "Click",
                        "DoubleClick",
                        "Excel"
                    ]
                },
                "editorHandlesTabEnter": {
                    "type": "boolean"
                },
                "enableEdit": {
                    "type": "boolean"
                }
            },
            "additionalProperties": false
        },
        "SortOptions": {
            "type": "object",
            "properties": {
                "sorNumeric": {
                    "type": "boolean"
                },
                "sortCaseInsensitive": {
                    "type": "boolean"
                }
            },
            "additionalProperties": false
        },
        "FilterOptions": {
            "type": "object",
            "properties": {
                "filterType": {
                    "type": "string",
                    "enum": [
                        "None",
                        "Text",
                        "Number",
                        "Date",
                        "Boolean",
                        "MultiSelect",
                        "SingleSelect"
                    ]
                },
                "filterExcludeObjectsWithoutMatchField": {
                    "type": "boolean"
                },
                "filterOperation": {
                    "type": "string",
                    "enum": [
                        "None",
                        "Equals",
                        "NotEquals",
                        "BeginsWith",
                        "Wildcard",
                        "EndsWith",
                        "Contains",
                        "DoesNotContain",
                        "GreaterThan",
                        "LessThan",
                        "GreaterThanEquals",
                        "LessThanEquals",
                        "InList",
                        "NotInList",
                        "Between",
                        "IsNotNull",
                        "IsNull"
                    ]
                },
                "excludeFromQuickFind": {
                    "type": "boolean"
                },
                "filterWaterMark": {
                    "type": "string"
                },
                "delayedChangeDuration": {
                    "type": "integer",
                    "minimum": 0
                },
                "useLabelFunctionForFilterCompare": {
                    "type": "boolean"
                },
                "blankValuesLabel": {
                    "type": "string"
                }
            }
        }
    }
}

=== flexicious/react-data-grid/apps/lambda-genie-demo/shared/lambda-genie/setup/config/GRID_COLUMN_DEFINITION.json
[
    {
      "dataField": "schools.CDSCode",
      "headerText": "CDS Code",
      "uniqueIdentifier": "schools.CDSCode",
      "format": "string",
      "filterOptions": {
        "filterOperation": "InList",
        "filterComboBoxBuildFromGrid": true
      },
      "lockMode": "none"
    },
    {
      "dataField": "schools.School",
      "headerText": "School Name",
      "uniqueIdentifier": "schools.School",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Contains",
        "filterOperation": "Contains"
      },
      "lockMode": "left"
    },
    {
      "dataField": "schools.District",
      "headerText": "District Name",
      "uniqueIdentifier": "schools.District",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "*search*",
        "filterOperation": "Wildcard"
      },
      "lockMode": "left"
    },
    {
      "dataField": "schools.NCESDist",
      "headerText": "NCES District",
      "uniqueIdentifier": "schools.NCESDist",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "lockMode": "none"
    },
    {
      "dataField": "schools.NCESSchool",
      "headerText": "NCES School",
      "uniqueIdentifier": "schools.NCESSchool",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      }
    },
    {
      "dataField": "schools.StatusType",
      "headerText": "Status",
      "uniqueIdentifier": "schools.StatusType",
      "format": "string",
      "filterOptions": {
        "filterOperation": "InList",
        "filterComboBoxBuildFromGrid": true
      }
    },
    {
      "dataField": "schools.County",
      "headerText": "County",
      "uniqueIdentifier": "schools.County",
      "format": "string",
      "filterOptions": {
        "filterOperation": "InList",
        "filterComboBoxBuildFromGrid": true
      }
    },
    {
      "dataField": "schools.Street",
      "headerText": "Street",
      "uniqueIdentifier": "schools.Street",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "hidden": false,
      "children": [
        {
          "dataField": "schools.StreetAbr",
          "headerText": "Street Abr",
          "uniqueIdentifier": "schools.StreetAbr",
          "format": "string",
          "filterOptions": {
            "filterWaterMark": "Begins With",
            "filterOperation": "BeginsWith"
          },
          "hidden": true
        },
        {
          "dataField": "schools.City",
          "headerText": "City",
          "uniqueIdentifier": "schools.City",
          "format": "string",
          "filterOptions": {
            "filterOperation": "InList",
            "filterComboBoxBuildFromGrid": true
          },
          "hidden": true
        },
        {
          "dataField": "schools.State",
          "headerText": "State",
          "uniqueIdentifier": "schools.State",
          "format": "string",
          "filterOptions": {
            "filterWaterMark": "Begins With",
            "filterOperation": "BeginsWith"
          },
          "hidden": true
        },
        {
          "dataField": "schools.Zip",
          "headerText": "Zip",
          "uniqueIdentifier": "schools.Zip",
          "format": "string",
          "filterOptions": {
            "filterWaterMark": "Begins With",
            "filterOperation": "BeginsWith"
          },
          "hidden": true
        }
      ]
    },
    {
      "dataField": "schools.MailStreet",
      "headerText": "Mail Street",
      "uniqueIdentifier": "schools.MailStreet",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "hidden": false,
      "children": [
        {
          "dataField": "schools.MailStrAbr",
          "headerText": "Mail Str Abr",
          "uniqueIdentifier": "schools.MailStrAbr",
          "format": "string",
          "filterOptions": {
            "filterWaterMark": "Begins With",
            "filterOperation": "BeginsWith"
          },
          "hidden": true
        },
        {
          "dataField": "schools.MailCity",
          "headerText": "Mail City",
          "uniqueIdentifier": "schools.MailCity",
          "format": "string",
          "filterOptions": {
            "filterWaterMark": "Begins With",
            "filterOperation": "BeginsWith"
          },
          "hidden": true
        },
        {
          "dataField": "schools.MailState",
          "headerText": "Mail State",
          "uniqueIdentifier": "schools.MailState",
          "format": "string",
          "filterOptions": {
            "filterWaterMark": "Begins With",
            "filterOperation": "BeginsWith"
          },
          "hidden": true
        },
        {
          "dataField": "schools.MailZip",
          "headerText": "Mail Zip",
          "uniqueIdentifier": "schools.MailZip",
          "format": "string",
          "filterOptions": {
            "filterWaterMark": "Begins With",
            "filterOperation": "BeginsWith"
          },
          "hidden": true
        }
      ]
    },
    {
      "dataField": "schools.Phone",
      "headerText": "Phone",
      "uniqueIdentifier": "schools.Phone",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "hidden": true
    },
    {
      "dataField": "schools.Ext",
      "headerText": "Ext",
      "uniqueIdentifier": "schools.Ext",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "hidden": true
    },
    {
      "dataField": "schools.Website",
      "headerText": "Website",
      "uniqueIdentifier": "schools.Website",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "hidden": true
    },
    {
      "dataField": "schools.OpenDate",
      "headerText": "Open Date",
      "uniqueIdentifier": "schools.OpenDate",
      "format": "date",
      "textAlign": "right",
      "filterOptions": {
        "filterOperation": "Between"
      },
      "hidden": true
    },
    {
      "dataField": "schools.ClosedDate",
      "headerText": "Closed Date",
      "uniqueIdentifier": "schools.ClosedDate",
      "format": "date",
      "textAlign": "right",
      "filterOptions": {
        "filterOperation": "Between"
      },
      "hidden": true
    },
    {
      "dataField": "schools.Charter",
      "headerText": "Charter",
      "uniqueIdentifier": "schools.Charter",
      "format": "boolean",
      "textAlign": "center",
      "filterOptions": {
        "filterOperation": "Equals",
        "filterComparisonType": "Boolean"
      },
      "hidden": true
    },
    {
      "dataField": "schools.CharterNum",
      "headerText": "Charter Num",
      "uniqueIdentifier": "schools.CharterNum",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "hidden": true
    },
    {
      "dataField": "schools.FundingType",
      "headerText": "Funding Type",
      "uniqueIdentifier": "schools.FundingType",
      "format": "string",
      "filterOptions": {
        "filterOperation": "InList",
        "filterComboBoxBuildFromGrid": true
      }
    },
    {
      "dataField": "schools.DOC",
      "headerText": "DOC",
      "uniqueIdentifier": "schools.DOC",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "hidden": true
    },
    {
      "dataField": "schools.DOCType",
      "headerText": "DOC Type",
      "uniqueIdentifier": "schools.DOCType",
      "format": "string",
      "filterOptions": {
        "filterOperation": "InList",
        "filterComboBoxBuildFromGrid": true
      }
    },
    {
      "dataField": "schools.SOC",
      "headerText": "SOC",
      "uniqueIdentifier": "schools.SOC",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "hidden": true
    },
    {
      "dataField": "schools.SOCType",
      "headerText": "SOC Type",
      "uniqueIdentifier": "schools.SOCType",
      "format": "string",
      "filterOptions": {
        "filterOperation": "InList",
        "filterComboBoxBuildFromGrid": true
      }
    },
    {
      "dataField": "schools.EdOpsCode",
      "headerText": "Ed Ops Code",
      "uniqueIdentifier": "schools.EdOpsCode",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "hidden": true
    },
    {
      "dataField": "schools.EdOpsName",
      "headerText": "Ed Ops Name",
      "uniqueIdentifier": "schools.EdOpsName",
      "format": "string",
      "filterOptions": {
        "filterOperation": "InList",
        "filterComboBoxBuildFromGrid": true
      },
      "hidden": true
    },
    {
      "dataField": "schools.EILCode",
      "headerText": "EIL Code",
      "uniqueIdentifier": "schools.EILCode",
      "format": "string",
      "filterOptions": {
        "filterWaterMark": "Begins With",
        "filterOperation": "BeginsWith"
      },
      "hidden": true
    },
    {
      "dataField": "schools.EILName",
      "headerText": "EIL Name",
      "uniqueIdentifier": "schools.EILName",
      "format": "string",
      "filterOptions": {
        "filterOperation": "InList",
        "filterComboBoxBuildFromGrid": true
      }
    },
    {
      "dataField": "schools.GSoffered",
      "headerText": "G Soffered",
      "uniqueIdentifier": "schools.GSoffered",
